name: Release Binaries

on:
  push:
    tags:
      - 'v*' # This captures when there's a new tag starting with a number (AKA a new version)

permissions:
  contents: write
  
jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: pngtosvg-linux
            binary_name: pngtosvg
            archive_name: pngtosvg-linux.tar.gz
          - os: windows-latest
            asset_name: pngtosvg-windows.exe
            binary_name: pngtosvg.exe
            archive_name: pngtosvg-windows.zip
          - os: macos-latest
            asset_name: pngtosvg-macos
            binary_name: pngtosvg
            archive_name: pngtosvg-macos.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        shell: bash
        run: |
          cargo build --release

      - name: Prepare Artifacts (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/release
          tar -czf ../../${{ matrix.archive_name }} ${{ matrix.binary_name }}

      - name: Prepare Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/release
          7z a ../../${{ matrix.archive_name }} ${{ matrix.binary_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.archive_name }}