name: Release Binaries

on:
  push:
    tags:
      - 'v*' # This captures when there's a new tag starting with a number (AKA a new version)

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: pngtosvg-linux
            binary_name: pngtosvg
          - os: windows-latest
            asset_name: pngtosvg-windows.exe
            binary_name: pngtosvg.exe
          - os: macos-latest
            asset_name: pngtosvg-macos
            binary_name: pngtosvg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install the Rust toolchain
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Build the project
      - name: Build project
        shell: bash
        run: |
          cargo build --release

      # Rename the binary to include the OS name (e.g., pngtosvg -> pngtosvg-linux)
      - name: Prepare Artifacts
        shell: bash
        run: |
          mv target/release/${{ matrix.binary_name }} ${{ matrix.asset_name }}

      # Upload the binary to the release page
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset_name }}
          fail_on_unmatched_files: true